### ISSUE TITLE
The meaning of turk_label?

### ISSUE THREAD

**Issue by yangky11** [harsh19/Reasoning-Chains-MultihopQA#2]
Hi,

Thanks for releasing the code!

I have a question about the meaning of `turk_label` in eQASC. For example, in [explore_data.ipynb](https://github.com/harsh19/Reasoning-Chains-MultihopQA/blob/master/data/explore_data.ipynb), there are a few different values for `turk_label`:
* `{"label": "yes"}`
* `{"label": "no"}`
* `{"label": "?"}`
* `{"label": "fact1"}`

If I understand correctly, "yes" and "no" just mean whether the reasoning step is valid. But what do "?" and "fact1" mean? Thank you!

**Comment by harsh19** [comment]
'fact1' or 'fact2' means that only fact alone can explain the answer.
'?' implies that the annotators disagreed (we treat such chains as a 'no' in the experiments).
